application: ntu-ecoliving2
version: 1
runtime: python
api_version: 1

handlers:

# HTML
# statistical
- url: /html/statistical/
  script: html/Statistical.py

# Document
# css
- url: /css
  static_dir: document/css
# js
- url: /js
  static_dir: document/js
# Script
- url: /(|example/)
  script: Root.py

# Tool
# Memcache
- url: /tool/memcache/
  script: tool/ToolPage.py
  
# Not Found Page
- url: /.*
  script: NotFound.py